/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 public/michelangelos_david_optimised.glb -o src/components/David.jsx -r public 
Author: Thomas Flynn (https://sketchfab.com/nebulousflynn)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/head-of-michelangelos-david-optimised-d29af50360624e5e9b1855666475380d
Title: Head Of Michelangelo's David, Optimised
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { useFrame } from '@react-three/fiber';


export function DavidModel(props) {
  const ref = useRef();

  useFrame(({ clock }) => {
    const a = clock.getElapsedTime() * 0.1;
    ref.current.rotation.y = a;
  })

  const { nodes, materials } = useGLTF('david.glb')
  // console.log(materials);
  materials.material_0.metalness = 1;
  materials.material_0.roughness = 0.4;
  materials.material_0.color.r = 100;
  materials.material_0.color.g = 100;
  materials.material_0.color.b = 180;

  return (
    <group {...props} dispose={null}>
      <mesh 
      ref={ref}
      geometry={nodes.Object_2.geometry} 
      material={materials.material_0}
      position={[0, 1, -8]} 
      rotation={[3.129, 0, 0]} 
      scale={0.065}
      />
    </group>
  )
}

useGLTF.preload('david.glb')
